import{a as B,S as m,i}from"./assets/vendor-DTWVMNYS.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const R="https://pixabay.com/api/",x="23963114-6d0d5d874ae460d9125bacd21";async function f(r,t=1){const a={key:x,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await B.get(R,{params:a})).data}let A=new m(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const t=document.querySelector(".gallery"),a=r.map(({webformatURL:s,largeImageURL:e,tags:o,likes:n,views:P,comments:M,downloads:$})=>`
        <li class="gallery-item">
          <a href="${e}" class="gallery-link">
            <img src="${s}" alt="${o}" class="gallery-image" />
          </a>
          <div class="image-info">
            <div class="image-info-item"><span><b>Likes</b></span><span>${n}</span></div>
            <div class="image-info-item"><span><b>Views</b></span><span>${P}</span></div>
            <div class="image-info-item"><span><b>Comments</b></span><span>${M}</span></div>
            <div class="image-info-item"><span><b>Downloads</b></span><span>${$}</span></div>
          </div>
        </li>
      `).join("");t.insertAdjacentHTML("beforeend",a),A.refresh()}function D(){document.querySelector(".gallery").innerHTML=""}const y=document.querySelector(".load-more"),L=document.querySelector(".loader-wrapper");function b(){L.classList.remove("is-hidden")}function d(){L.classList.add("is-hidden")}function E(){y.classList.remove("is-hidden")}function p(){y.classList.add("is-hidden")}const v=document.querySelector(".form"),O=document.querySelector(".load-more"),w=v.querySelector('input[name="search-text"]');let l="",c=1;const S=15;let g=0,u=null;document.addEventListener("click",r=>{(r.target.classList.contains("sl-close")||r.target.classList.contains("sl-overlay"))&&w.blur()});v.addEventListener("submit",async function(r){if(r.preventDefault(),l=w.value.trim(),!l){i.info({message:"Please enter a search term.",position:"topRight"});return}c=1,D(),p(),b();try{const{hits:t,totalHits:a}=await f(l,c);if(d(),t.length===0){i.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g=a,h(t),q(),Math.ceil(g/S)>1?E():(p(),i.info({message:"The end of search results.",position:"topRight"}))}catch{d(),i.error({message:"An error occurred while fetching data. Please try again.",position:"topRight"})}});O.addEventListener("click",async()=>{c+=1,b();try{const{hits:r}=await f(l,c);d(),h(r),q();const t=Math.ceil(g/S);c>=t&&(p(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const a=document.querySelector(".gallery-item");if(a){const{height:s}=a.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}catch{d(),i.error({message:"An error occurred while fetching more data.",position:"topRight"})}});function q(){u&&u.destroy(),u=new m(".gallery a",{captionsData:"alt",captionDelay:250,nav:!0,loop:!1})}
//# sourceMappingURL=index.js.map
