import{a as M,S as f,i}from"./assets/vendor-DTWVMNYS.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const $="https://pixabay.com/api/",x="23963114-6d0d5d874ae460d9125bacd21";async function h(s,t=1){const r={key:x,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await M.get($,{params:r})).data}let B=new f(".gallery a",{captionsData:"alt",captionDelay:250});function y(s){const t=document.querySelector(".gallery"),r=s.map(({webformatURL:a,largeImageURL:e,tags:o,likes:n,views:P,comments:S,downloads:q})=>`
        <li class="gallery-item">
          <a href="${e}" class="gallery-link">
            <img src="${a}" alt="${o}" class="gallery-image" />
          </a>
          <div class="image-info">
            <div class="image-info-item"><span><b>Likes</b></span><span>${n}</span></div>
            <div class="image-info-item"><span><b>Views</b></span><span>${P}</span></div>
            <div class="image-info-item"><span><b>Comments</b></span><span>${S}</span></div>
            <div class="image-info-item"><span><b>Downloads</b></span><span>${q}</span></div>
          </div>
        </li>
      `).join("");t.insertAdjacentHTML("beforeend",r),B.refresh()}function R(){document.querySelector(".gallery").innerHTML=""}const b=document.querySelector(".load-more"),v=document.querySelector(".loader-wrapper");function L(){v.classList.remove("is-hidden")}function d(){v.classList.add("is-hidden")}function A(){b.classList.remove("is-hidden")}function u(){b.classList.add("is-hidden")}const p=document.querySelector(".form"),D=document.querySelector(".load-more");let l="",c=1;const w=15;let m=0;const g=new f(".gallery a",{captionsData:"alt",captionDelay:250});g.on("closed.simplelightbox",()=>{p.elements["search-text"].focus()});p.addEventListener("submit",async function(s){if(s.preventDefault(),l=p.elements["search-text"].value.trim(),!l){i.info({message:"Please enter a search term.",position:"topRight"});return}c=1,R(),u(),L();try{const{hits:t,totalHits:r}=await h(l,c);if(d(),t.length===0){i.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m=r,y(t),g.refresh(),Math.ceil(m/w)>1?A():(u(),i.info({message:"The end of search results.",position:"topRight"}))}catch{d(),i.error({message:"An error occurred while fetching data. Please try again.",position:"topRight"})}});D.addEventListener("click",async()=>{c+=1,L();try{const{hits:s}=await h(l,c);d(),y(s),g.refresh();const t=Math.ceil(m/w);c>=t&&(u(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const r=document.querySelector(".gallery-item");if(r){const{height:a}=r.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}}catch{d(),i.error({message:"An error occurred while fetching more data.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
