import{a as M,S as g,i}from"./assets/vendor-DTWVMNYS.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const $="https://pixabay.com/api/",B="23963114-6d0d5d874ae460d9125bacd21";async function f(a,t=1){const r={key:B,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await M.get($,{params:r})).data}let R=new g(".gallery a",{captionsData:"alt",captionDelay:250});function h(a){const t=document.querySelector(".gallery"),r=a.map(({webformatURL:s,largeImageURL:e,tags:o,likes:n,views:P,comments:S,downloads:q})=>`
        <li class="gallery-item">
          <a href="${e}" class="gallery-link">
            <img src="${s}" alt="${o}" class="gallery-image" />
          </a>
          <div class="image-info">
            <div class="image-info-item"><span><b>Likes</b></span><span>${n}</span></div>
            <div class="image-info-item"><span><b>Views</b></span><span>${P}</span></div>
            <div class="image-info-item"><span><b>Comments</b></span><span>${S}</span></div>
            <div class="image-info-item"><span><b>Downloads</b></span><span>${q}</span></div>
          </div>
        </li>
      `).join("");t.insertAdjacentHTML("beforeend",r),R.refresh()}function x(){document.querySelector(".gallery").innerHTML=""}const y=document.querySelector(".load-more"),b=document.querySelector(".loader-wrapper");function v(){b.classList.remove("is-hidden")}function d(){b.classList.add("is-hidden")}function A(){y.classList.remove("is-hidden")}function u(){y.classList.add("is-hidden")}const m=document.querySelector(".form"),D=document.querySelector(".load-more");let l="",c=1;const L=15;let p=0;const w=new g(".gallery a",{captionsData:"alt",captionDelay:250});m.addEventListener("submit",async function(a){if(a.preventDefault(),l=m.elements["search-text"].value.trim(),!l){i.info({message:"Please enter a search term.",position:"topRight"});return}c=1,x(),u(),v();try{const{hits:t,totalHits:r}=await f(l,c);if(d(),t.length===0){i.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p=r,h(t),w.refresh(),Math.ceil(p/L)>1?A():(u(),i.info({message:"The end of search results.",position:"topRight"}))}catch{d(),i.error({message:"An error occurred while fetching data. Please try again.",position:"topRight"})}});D.addEventListener("click",async()=>{c+=1,v();try{const{hits:a}=await f(l,c);d(),h(a),w.refresh();const t=Math.ceil(p/L);c>=t&&(u(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const r=document.querySelector(".gallery-item");if(r){const{height:s}=r.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}catch{d(),i.error({message:"An error occurred while fetching more data.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
